env: prod
driver:
  timeout: 10 # unit: second
  browser: "chrome" # or "firefox", "edge"
  window_size:
    width: 1920
    height: 1080

environments:
  prod: "https://www.saucedemo.com"
  qa: "https://www.saucedemo.com"
  staging: "https://www.saucedemo.com"